name: knighthorse
description: knighthorse

publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  twilio_flutter: ^0.9.0 # Check for the latest version
  url_launcher: ^6.3.0
  pdf: ^3.10.4
  printing: ^5.11.0
  mailer: ^6.0.0

  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.0
  get_storage: ^2.1.1
  logger: ^2.6.1
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  image_picker: ^1.2.0
  flutter_svg: ^2.2.0
  flutter_animate: ^4.5.2
  connectivity_plus: ^6.1.5
  flutter_inappwebview: ^6.1.5
  r_dotted_line_border: ^0.1.1
  carousel_slider: ^5.1.1
  loading_animation_widget: ^1.3.0
  iconsax: ^0.0.8
  flip_card: ^0.7.0
  permission_handler: ^12.0.1
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  restart_app: ^1.3.2
  # custom_date_range_picker:
  path_provider: ^2.1.5
  open_file: ^3.5.10
  dots_indicator: ^4.0.1
  shimmer: ^3.0.0
  flutter_html: ^3.0.0
  phone_form_field: ^10.0.8
  lottie: ^3.3.1
  sqflite: ^2.4.2
  dynamic_languages:
    git:
      url: https://github.com/appdevsx/dynamic_languages
      ref: main
  google_sign_in: ^6.2.2
  path: ^1.9.1
  sendotp_flutter_sdk: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  # dart_code_metrics: any
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1
  rename_app: ^1.6.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/app_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
    - assets/animation/
  fonts:
    - family: Technor
      fonts:
        - asset: assets\fonts\technor.otf